name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  page_build:
  release:
    types:
      - created
      - edited
      - prereleased
      - released

env:
  # Build a release build
  BUILD_TYPE: Release
  # MSVC installation directory
  VCINSTALLDIR: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/

jobs:
  windows:
    timeout-minutes: 15
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019"

    - name: Compile
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      working-directory: build
      shell: cmd
      run: cmake --build . --config Release --target package

    - name: Upload Artifact
      working-directory: build
      - uses: actions/upload-artifact@v3
      with:
        name: build
        path: DesignerVersionChooser*.exe